### ISSUE TITLE
Diferencias | Diferrences

### ISSUE THREAD

**Issue by fdenia** [Josantonius/PHP-DataType#1]
Que diferencias hay entre tu script y utilizar lo siguiente? 
$std = new StdClass();
	$std->name = 'Fran';
	$std->lastname = 'Denia';
	$std->age      = '19';
var_dump((array)$std);

Gracias!

------

What differences are there between your script and use the following?
$std = new StdClass();
	$std->name = 'Fran';
	$std->lastname = 'Denia';
	$std->age      = '19';
var_dump((array)$std);
Thanks!

**Comment by Josantonius** [comment]
La diferencia está en que el script lo hace de manera recursiva y en este caso solo convierte el primer elemento.

```
$std = new StdClass();

$std->obj = new StdClass();

var_dump((array) $std); // array(1) { ["obj"] => object(0) {} }

var_dump(DataType::objectToArray($std)); // array(1) { ["obj"] => array(0) {} }
```

¡Un saludo! :wink:

**Comment by fdenia** [comment]
Genial! Estrella entonces!
